# Build stage
FROM golang:1.21-alpine AS builder

RUN apk add --no-cache git make

WORKDIR /app/app

COPY go.mod go.sum ./
RUN go mod download

COPY deploy/ .
RUN go install github.com/cosmtrek/air@latest

# Runtime stage
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/bin/modeler .

CMD ["air", "-c", "/app/app/.air.modeler.toml"]
